# Generated by Django 5.1.2 on 2024-10-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="default_name", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
