# Generated by Django 5.1.2 on 2024-10-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_inventorychange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("contact", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="minimum",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="item",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.supplier",
            ),
        ),
    ]
