# Generated by Django 5.1.2 on 2024-10-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_supplier_item_minimum_item_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
